### PR TITLE
Update install_Applio.sh All permission to execute code without any r…

### PR DESCRIPTION
**Pull request by Anthonyxd22**
Update go-applio.sh All permission to execute code without any restrictions…  on Linux and its variants and Mac

### CODE REVIEW

**Comment by Aldair502** [comment]
this doesn't make any sence

**Comment by Anthonyxd22** [comment]
That is useful for Linux and some of its variants that need to be entered because it saves writing it to be able to run it.

**Comment by Aldair502** [comment]
> That is useful for Linux and some of its variants that need to be entered because it saves writing it to be able to run it.

then just use "bash script.sh". this line literally does nothing about it

**Comment by Anthonyxd22** [comment]
Sorry, I didn't realize that the code was already there, thanks for letting me know.

**Comment by Aldair502** [comment]
> Sorry, I didn't realize that the code was already there, thanks for letting me know.

may what you can do is do a chmod +x *.sh after update applio cuz that don't bring back the perms

**Pull request closed without merging**
