### PR TITLE
Update go-tensorboard.sh Fix

### PR DESCRIPTION
**Pull request by Anthonyxd22**
to avoid unnecessary reinstallation etc...

### CODE REVIEW

**Comment by Anthonyxd22** [comment]
Captura de pantalla 2023-12-03 a la(s) 10 32 21 a m Con en codigo que hice

**Comment by Anthonyxd22** [comment]
Captura de pantalla 2023-12-03 a la(s) 10 33 47 a m this in previous code literally reinstall everything slower etc...

**Comment by Aldair502** [comment]
but it doesn't use conda wth

**Comment by Anthonyxd22** [comment]
nahh but it is much faster and thus saves you having to reinstall everything xd

**Comment by Aldair502** [comment]
> nahh but it is much faster and thus saves you having to reinstall everything xd

literally it doesn't do anything. the install script always check if .venv already exists before create it lol. change to conda may broke some code already related to venv

**Pull request closed without merging**
